### ISSUE TITLE
About the version of open3d

### ISSUE THREAD

**Issue by wangxiaochu** [IntelVCL/Open3D-PointNet2-Semantic3D#26]
@yxlao ，When I run downsample.py, I get the error "module 'open3d.open3d' has no attribute 'voxel_down_sample_and_trace'". I went to view the open3d library. I didn't find the attribute, but I saw "voxel_down_sample", but this one has another Problem, the contents that needs to be filled in are different. So I guess the version of open3d we use is different. The version I use is 0.4. What about you? I need your help. Thank you!

**Comment by yxlao** [comment]
Need to compile from source to get the latest version
